"""Seed-data integrity tests.

These guard the evidence-integrity rules from the build spec:
no fabricated quantitative metrics, citations on every claim, and
protocol parameters preserved on every modifier.

The isolated test database is created and seeded when synlethality.main is
imported (see conftest.py for the temp DATABASE_URL).
"""

import pytest
from sqlalchemy import select

from synlethality.main import SessionLocal  # auto-seeds on import
from synlethality.models import (
    CellLine,
    ClinicalEvidence,
    DrugResistanceMechanism,
    EvidenceTier,
    InteractionEffect,
    InteractionType,
    Modifier,
    ModifierType,
    StressSignatureScore,
    TumorConcordanceFlag,
)
from synlethality.seed_data import seed


def _all(model, **filters):
    with SessionLocal() as db:
        stmt = select(model)
        for k, v in filters.items():
            stmt = stmt.where(getattr(model, k) == v)
        return db.scalars(stmt).all()


def test_tier_distribution():
    counts = {
        tier: len(_all(InteractionEffect, evidence_tier=tier))
        for tier in EvidenceTier
    }
    # +3 vs. the pre-Track-C count: Kusumoto et al. 1993 (PMID 8347479)
    # simultaneous cisplatin, simultaneous carboplatin, and heat-before
    # carboplatin (survival-slope ratio 2.85, added 2026-09-24).
    assert counts[EvidenceTier.tier_1_direct] == 30
    assert counts[EvidenceTier.tier_2_inferred] == 4
    # 5 hand-curated mechanism-only rows + 19 generated by the Mechanistic
    # Bridging module (synlethality/bridging.py) -- see
    # test_bridging_candidates_are_well_formed for the generated-row checks.
    # (+2 vs. earlier: triapine_rrm2's dna_damage-panel tag matches the
    # existing fasting/TTFields dna_damage signatures.)
    assert counts[EvidenceTier.tier_3_mechanism_only] == 24


def test_every_interaction_cited():
    allowed = ("pmid:", "doi:", "geo:", "sra:", "gdc:", "depmap:")
    for it in _all(InteractionEffect):
        assert it.source_study, f"{it.id} has no citation"
        for c in it.source_study:
            assert c.startswith(allowed), f"unrecognised citation format: {c}"


def test_tier2_has_mechanism_link():
    for it in _all(InteractionEffect, evidence_tier=EvidenceTier.tier_2_inferred):
        assert it.mechanism_link is not None, (
            "Tier-2 (inferred) claims require a linked stress signature")


#: (modifier_id, drug_id, cell_line_id) -> real, source-verified
#: combined_effect_metric, extracted 2026-09-23 directly from each paper's own
#: reported numbers (never computed/estimated here) -- see seed_data.py's
#: curator_notes on each row for the exact source quote and metric
#: definition (Thermal Enhancement Ratio for the HIPEC row; IC50 fold-shift
#: for the four stiffness rows). Every other curated row must still carry
#: combined_effect_metric=None -- this project's core evidence-integrity
#: rule (no fabricated/estimated numbers) is unchanged, this is just the
#: first real exception to "no row has one yet".
REAL_COMBINED_EFFECT_METRICS = {
    ("MOD-HT-42C-60M-HIPEC", "carboplatin", "RKO_LARGE_INTESTINE"): 3.8,
    ("MOD-STIFFNESS-53KPA-5G5P", "doxorubicin", "MDAMB231_BREAST"): 4.71,
    ("MOD-STIFFNESS-53KPA-5G5P", "paclitaxel", "MDAMB231_BREAST"): 6.65,
    ("MOD-STIFFNESS-53KPA-5G5P", "doxorubicin", "MCF7_BREAST"): 4.3,
    ("MOD-STIFFNESS-53KPA-5G5P", "paclitaxel", "MCF7_BREAST"): 3.77,
    # Track C, 2026-09-23: Kusumoto et al. 1993 (PMID 8347479), real
    # survival-curve-slope enhancement ratios, simultaneous 42.8C heat schedule.
    ("MOD-HT-42.8C-30M-SIMUL", "cisplatin", "HELA_CERVIX"): 3.10,
    ("MOD-HT-42.8C-30M-SIMUL", "carboplatin", "HELA_CERVIX"): 2.96,
    # Discussion sentence, heat prior to carboplatin: survival effect 2.85
    # (the paired 2.75 is platinum accumulation, not this metric).
    ("MOD-HT-42.8C-30M-BEFORE", "carboplatin", "HELA_CERVIX"): 2.85,
    # Helderman 2020 PDF, 2026-09-24. Temperatures are the ones the sentence names.
    ("MOD-HT-41C-60M-HIPEC", "carboplatin", "RKO_LARGE_INTESTINE"): 2.5,
    ("MOD-HT-43C-60M-HIPEC", "carboplatin", "RKO_LARGE_INTESTINE"): 7.2,
    ("MOD-HT-43C-60M-HIPEC", "oxaliplatin", "RKO_LARGE_INTESTINE"): 3.3,
    ("MOD-HT-43C-60M-HIPEC", "oxaliplatin", "HCT116_LARGE_INTESTINE"): 3.1,
    ("MOD-HT-43C-60M-HIPEC", "cisplatin", "RKO_LARGE_INTESTINE"): 3.5,
    ("MOD-HT-43C-60M-HIPEC", "cisplatin", "HCT116_LARGE_INTESTINE"): 2.8,
}


def test_no_fabricated_combined_metrics():
    """Curated seed carries a combined-effect metric only where a paper's own
    number was directly extracted and cited (REAL_COMBINED_EFFECT_METRICS,
    2026-09-23) -- every other row stays qualitative-only (documented spec
    deviation), never an estimated or computed placeholder."""
    for it in _all(InteractionEffect):
        key = (it.modifier_id, it.drug_id, it.cell_line_id)
        if key in REAL_COMBINED_EFFECT_METRICS:
            assert it.combined_effect_metric == pytest.approx(REAL_COMBINED_EFFECT_METRICS[key])
        else:
            assert it.combined_effect_metric is None, (
                f"{key} has an unexpected combined_effect_metric -- add it to "
                "REAL_COMBINED_EFFECT_METRICS with its source, or this may be "
                "a fabricated/estimated value.")
    assert len(REAL_COMBINED_EFFECT_METRICS) == len([
        it for it in _all(InteractionEffect) if it.combined_effect_metric is not None
    ])


def test_every_signature_has_source():
    for s in _all(StressSignatureScore):
        assert s.raw_deg_evidence_ref, f"{s.id} missing raw_deg_evidence_ref"
        assert s.cell_line_id and s.modifier_id


def test_modifier_protocol_parameters_preserved():
    for m in _all(Modifier):
        assert isinstance(m.protocol_parameters, dict) and m.protocol_parameters, (
            f"{m.modifier_id} lost its protocol parameters")
    for m in _all(Modifier, modifier_type=ModifierType.thermal):
        params = m.protocol_parameters
        has_temp = "temperature_C" in params
        unreported = params.get("temperature_unreported") is True
        assert has_temp or unreported, (
            f"{m.modifier_id} is thermal but has neither temperature_C nor "
            "an explicit temperature_unreported flag")
        if unreported:
            assert "temperature_C" not in params


def test_human_physiology_modifiers_use_checked_accessions():
    """2026-09-24: fasting, feeding-window, exercise, cold, heat, light and
    mechanical series. Accessions were read from GEO the day they were added."""
    by_id = {m.modifier_id: m for m in _all(Modifier)}
    expected = {
        "MOD-FAST-24H-GSE55924": "GSE55924",
        "MOD-FAST-40H-GSE28016": "GSE28016",
        "MOD-TRF-8H-5D-GSE129843": "GSE129843",
        "MOD-TRE-10H-8WK-GSE168705": "GSE168705",
        "MOD-ENDURANCE-18WK-RUN": "GSE111551",
        "MOD-RESIST-ACUTE-GSE252357": "GSE252357",
        "MOD-EXERCISE-ACUTE-TREADMILL": "GSE3606",
        "MOD-COLD-ACCLIM-10D": "GSE156248",
        "MOD-COLD-VS-EXERCISE-GSE156249": "GSE156249",
        "MOD-CWI-10WK-STRENGTH": "GSE85620",
        "MOD-HEAT-CHAMBER-30M-GSE82323": "GSE82323",
        "MOD-HEAT-SHEET-10WK": "GSE12474",
        "MOD-HEAT-SAUNA-PBMC": "GSE90763",
        "MOD-PBM-BLUE-HACAT": "GSE82093",
        "MOD-BBL-SKIN-GSE39170": "GSE39170",
        "MOD-VIBRATION-LIMB-GSE82323": "GSE82323",
        "MOD-NMES-GSE82323": "GSE82323",
    }
    for modifier_id, accession in expected.items():
        assert by_id[modifier_id].source_dataset_accession == accession
    assert by_id["MOD-COLD-ACCLIM-10D"].protocol_parameters["temperature_C"] == "14-15"
    assert by_id["MOD-HEAT-CHAMBER-30M-GSE82323"].protocol_parameters["temperature_C"] == 73.0
    assert by_id["MOD-HEAT-SAUNA-PBMC"].protocol_parameters["temperature_C"] == 75.7
    assert by_id["MOD-CWI-10WK-STRENGTH"].protocol_parameters["temperature_unreported"] is True
    assert by_id["MOD-HEAT-SHEET-10WK"].protocol_parameters["temperature_unreported"] is True


def test_seed_is_idempotent():
    with SessionLocal() as db:
        n_before = len(db.scalars(select(InteractionEffect)).all())
        result = seed(db)
        n_after = len(db.scalars(select(InteractionEffect)).all())
    assert result["seeded"] is False
    assert n_before == n_after


def test_key_mutations_are_lists():
    for cl in _all(CellLine):
        assert isinstance(cl.key_mutations, list) and cl.key_mutations


def test_tumor_concordance_defaults_unassessed():
    """No fabricated Celligner scores: every curated line starts NULL/
    unassessed until ingest/celligner.py backfills real alignment output."""
    for cl in _all(CellLine):
        assert cl.tumor_concordance_score is None
        assert cl.tumor_concordance_flag == TumorConcordanceFlag.unassessed


def test_drug_resistance_mechanisms_are_cited():
    rows = _all(DrugResistanceMechanism)
    assert len(rows) >= 6
    allowed = ("pmid:", "doi:", "geo:")
    for drm in rows:
        assert drm.source.startswith(allowed), f"{drm.id} has an unrecognised citation format"
        assert drm.pathway_or_gene and drm.mechanism_description


def test_bridging_candidates_are_well_formed():
    """Every Mechanistic Bridging output row (resistance_mechanism_link set)
    must carry both links, be tier_3_mechanism_only, and never overwrite or
    duplicate a hand-curated (modifier_id, drug_id, cell_line_id) triple."""
    generated = [
        it for it in _all(InteractionEffect) if it.resistance_mechanism_link is not None
    ]
    assert len(generated) >= 10
    seen = set()
    for it in generated:
        assert it.evidence_tier == EvidenceTier.tier_3_mechanism_only
        assert it.mechanism_link is not None
        assert it.interaction_type in (InteractionType.synergistic, InteractionType.antagonistic)
        assert "Mechanistic Bridging" in it.curator_notes
        assert it.combined_effect_metric is None  # never a fabricated number
        triple = (it.modifier_id, it.drug_id, it.cell_line_id)
        assert triple not in seen, f"duplicate generated triple {triple}"
        seen.add(triple)


def test_candidates_endpoint_excludes_curated_mechanism_only_rows():
    """Hand-curated tier_3 rows (no resistance_mechanism_link) must never
    show up as if they were Mechanistic Bridging output."""
    curated_tier3 = [
        it for it in _all(InteractionEffect, evidence_tier=EvidenceTier.tier_3_mechanism_only)
        if it.resistance_mechanism_link is None
    ]
    assert len(curated_tier3) == 5  # pre-v5 hand-curated + HBOT mechanism-only rows


def test_oncotree_fields_default_null():
    """No fabricated OncoTree/NCIt codes: these come from DepMap's own
    Model.csv (ingest/depmap_prism.py), never guessed per cell line."""
    for cl in _all(CellLine):
        assert cl.oncotree_code is None
        assert cl.oncotree_primary_disease is None
        assert cl.oncotree_subtype is None
        assert cl.ncit_code is None


def test_depmap_prism_ingest_backfills_without_touching_curated_rows():
    """Real ingestion step (data/depmap/{Model,PortalCompounds}.csv,
    downloaded 2026-09-22 from the DepMap 24Q4 Figshare+ mirror): backfills
    OncoTree fields onto curated cell lines by real match, bulk-imports the
    DepMap compound registry as new drug rows, and never touches a single
    field of an already-curated drug or cell line."""
    from synlethality.ingest.depmap_prism import CURATED_DRUG_ALIASES, DepmapPrismIngest
    from synlethality.models import Drug

    with SessionLocal() as db:
        metformin_before = db.get(Drug, "metformin").to_dict()
        cisplatin_before = db.get(Drug, "cisplatin").to_dict()
        drug_count_before = len(_all(Drug))

        run = DepmapPrismIngest().run(db)
        assert run.status == "success", run.message
        assert run.row_count > 2000  # ~14 backfilled lines + ~6990 new compounds

        # Curated drugs completely untouched -- every field, not just a sample.
        assert db.get(Drug, "metformin").to_dict() == metformin_before
        assert db.get(Drug, "cisplatin").to_dict() == cisplatin_before

        # Real backfill landed on a real, independently-verified value.
        mcf7 = db.get(CellLine, "MCF7_BREAST")
        assert mcf7.oncotree_code == "BRCA"
        assert mcf7.oncotree_primary_disease == "Invasive Breast Carcinoma"
        u87 = db.get(CellLine, "U87MG_CENTRAL_NERVOUS_SYSTEM")
        assert u87.oncotree_code == "GB"

        # Lines with no DepMap match are left alone, never guessed.
        mouse_line = db.get(CellLine, "4T1_BREAST")
        assert mouse_line.oncotree_code is None
        isogenic = db.get(CellLine, "HCT116P53NULL_LARGE_INTESTINE")
        assert isogenic.oncotree_code is None

        # A large, real compound registry was actually added, not just claimed.
        new_drug_count = len(_all(Drug))
        assert new_drug_count - drug_count_before > 6900
        depmap_drugs = [d for d in _all(Drug) if d.drug_id.startswith("DPC-")]
        assert depmap_drugs
        for d in depmap_drugs[:20]:
            assert d.source == "DepMap 24Q4 PortalCompounds.csv"

        # Curated-drug identity collision fix: none of the 12 DepMap
        # CompoundIDs that duplicate a curated drug under a different name
        # (e.g. cisplatin as "CIS-DDP") get their own Drug row -- would
        # otherwise fragment identity and strand real PRISM viability data
        # (ingest/prism_repurposing.py) on a disconnected duplicate.
        for dpc_id, curated_id in CURATED_DRUG_ALIASES.items():
            assert db.get(Drug, dpc_id) is None, (
                f"{dpc_id} should never exist as a separate row from {curated_id}")
            assert db.get(Drug, curated_id) is not None

        # Idempotent: re-running doesn't duplicate rows.
        run2 = DepmapPrismIngest().run(db)
        assert run2.status == "success"
        assert len(_all(Drug)) == new_drug_count


def test_curated_bulk_mechanisms_and_rebridging():
    """Real, PMID-verified resistance-mechanism research for 8 bulk-registry
    drugs (synlethality/curated_bulk_mechanisms.py): must reference real
    DepMap drug_ids (only resolvable after ingestion), be correctly cited,
    and actually produce new real Tier 3 bridging output on re-run --
    proving the mechanisms are wired all the way through, not just inserted
    and ignored."""
    from synlethality import curated_bulk_mechanisms
    from synlethality.bridging import generate_candidates
    from synlethality.ingest.depmap_prism import DepmapPrismIngest
    from synlethality.models import Drug, DrugResistanceMechanism

    with SessionLocal() as db:
        DepmapPrismIngest().run(db)

        counts = curated_bulk_mechanisms.seed(db)
        db.commit()
        assert counts["inserted"] == len(curated_bulk_mechanisms.CURATED_BULK_RESISTANCE_MECHANISMS)

        for row in curated_bulk_mechanisms.CURATED_BULK_RESISTANCE_MECHANISMS:
            assert db.get(Drug, row["drug_id"]) is not None, (
                f"{row['drug_id']} must already exist from the DepMap ingest")
            assert row["source"].startswith(("pmid:", "doi:", "geo:"))

        # Idempotent.
        counts2 = curated_bulk_mechanisms.seed(db)
        db.commit()
        assert counts2["inserted"] == 0

        # Re-running bridging after these mechanisms exist must produce at
        # least one real, cited Tier 3 candidate for one of them (etoposide/
        # TOP2A is the one row tagged with a matchable signature_panel).
        etoposide_mechanism = (
            db.query(DrugResistanceMechanism)
            .filter_by(drug_id=curated_bulk_mechanisms.ETOPOSIDE)
            .one()
        )
        assert etoposide_mechanism.signature_panel is not None
        bridge_counts = generate_candidates(db)
        db.commit()
        assert bridge_counts["generated_synergistic"] + bridge_counts["generated_antagonistic"] > 0
        new_etoposide_rows = _all(InteractionEffect, drug_id=curated_bulk_mechanisms.ETOPOSIDE)
        assert new_etoposide_rows
        for it in new_etoposide_rows:
            assert it.resistance_mechanism_link == etoposide_mechanism.id
            assert it.evidence_tier == EvidenceTier.tier_3_mechanism_only


def test_heuristic_bridging_is_correctly_tiered_and_scoped():
    """Tier 4 (synlethality/heuristic_bridging.py): real DepMap target/
    mechanism text run through a documented keyword match -- must never be
    confused with the cited Tier 3 output (bridging.py), never claim a
    direction, and never duplicate a drug that already has a real,
    per-row-cited drug_resistance_mechanism."""
    from synlethality.heuristic_bridging import generate_heuristic_matches
    from synlethality.ingest.depmap_prism import DepmapPrismIngest
    from synlethality.models import DrugResistanceMechanism

    with SessionLocal() as db:
        DepmapPrismIngest().run(db)
        counts = generate_heuristic_matches(db)
        db.commit()
        assert counts["generated"] > 100  # a real, non-trivial match count

        tier4_rows = _all(InteractionEffect, evidence_tier=EvidenceTier.tier_4_heuristic_target_match)
        assert len(tier4_rows) == counts["generated"]

        drugs_with_real_mechanism = {
            row[0] for row in db.query(DrugResistanceMechanism.drug_id).all()
        }
        seen = set()
        for it in tier4_rows:
            # Never conflated with the cited bridging output.
            assert it.interaction_type == InteractionType.unknown
            assert it.resistance_mechanism_link is None
            assert it.mechanism_link is not None
            assert it.combined_effect_metric is None
            assert "Tier 4" in it.curator_notes
            # Never layered on top of a drug that already has real evidence.
            assert it.drug_id not in drugs_with_real_mechanism
            triple = (it.modifier_id, it.drug_id, it.cell_line_id)
            assert triple not in seen, f"duplicate heuristic triple {triple}"
            seen.add(triple)
            for c in it.source_study:
                assert c.startswith(("pmid:", "doi:", "geo:"))

        # Idempotent.
        counts2 = generate_heuristic_matches(db)
        db.commit()
        assert counts2["generated"] == 0
        assert len(_all(InteractionEffect,
                        evidence_tier=EvidenceTier.tier_4_heuristic_target_match)) == len(tier4_rows)


def test_nearest_neighbor_candidates_are_correctly_tiered_and_scoped():
    """Tier 2c (synlethality/nearest_neighbor.py, reconciling the "NPxP
    Interaction Predictor" build spec's Stage 1/E2 into this schema): a
    real modifier x drug pair borrowed from a real tier_1/tier_2 result in
    a molecularly/tissue-similar cell line -- never generated for a cell
    line that already has any row for that pair, never crossing a real
    tissue/lineage boundary (regression test for the false-positive found
    2026-09-23: RKO colorectal x MDA-MB-231 breast matched purely on a
    "wild-type" TP53 entry sharing a gene name with a real TP53 mutation)."""
    from synlethality.nearest_neighbor import (
        cell_line_similarity,
        generate_nearest_neighbor_candidates,
    )

    with SessionLocal() as db:
        # Regression check for the real bug found while building this:
        # a "wild-type" annotation must never count as a shared mutation,
        # and there must be a hard tissue/lineage gate.
        rko = db.get(CellLine, "RKO_LARGE_INTESTINE")
        mda = db.get(CellLine, "MDAMB231_BREAST")
        assert cell_line_similarity(rko, mda) == 0.0

        counts = generate_nearest_neighbor_candidates(db)
        db.commit()
        assert counts["generated"] > 20  # a real, non-trivial count

        tier2c_rows = _all(InteractionEffect, evidence_tier=EvidenceTier.tier_2c_nearest_neighbor)
        assert len(tier2c_rows) == counts["generated"]

        real_rows = (
            _all(InteractionEffect, evidence_tier=EvidenceTier.tier_1_direct)
            + _all(InteractionEffect, evidence_tier=EvidenceTier.tier_2_inferred)
        )
        real_triples = {(r.modifier_id, r.drug_id, r.cell_line_id) for r in real_rows}
        real_pairs_by_donor_tissue = {}
        for r in real_rows:
            cl = db.get(CellLine, r.cell_line_id)
            real_pairs_by_donor_tissue.setdefault((r.modifier_id, r.drug_id), set()).add(cl.tissue_origin)

        seen = set()
        for it in tier2c_rows:
            triple = (it.modifier_id, it.drug_id, it.cell_line_id)
            # Never generated for a cell line that already has a real row
            # for this exact pair.
            assert triple not in real_triples
            assert triple not in seen, f"duplicate nearest-neighbor triple {triple}"
            seen.add(triple)
            # Never a fabricated citation -- always the real donor's own.
            assert it.source_study, f"{triple} has no citation"
            for c in it.source_study:
                assert c.startswith(("pmid:", "doi:", "geo:"))
            assert "Nearest-neighbor" in it.curator_notes
            assert it.resistance_mechanism_link is None
            # Never crosses into a tissue the real donor(s) weren't in.
            target_cl = db.get(CellLine, it.cell_line_id)
            donor_tissues = real_pairs_by_donor_tissue[(it.modifier_id, it.drug_id)]
            assert target_cl.tissue_origin in donor_tissues, (
                f"{triple} extrapolated across a tissue boundary "
                f"({target_cl.tissue_origin} not in {donor_tissues})")

        # Idempotent.
        counts2 = generate_nearest_neighbor_candidates(db)
        db.commit()
        assert counts2["generated"] == 0
        assert len(_all(InteractionEffect,
                        evidence_tier=EvidenceTier.tier_2c_nearest_neighbor)) == len(tier2c_rows)


def test_nearest_neighbor_never_uses_poor_model_line_as_donor():
    """A cell line flagged poor_model_mesenchymal_shift must never be used
    as a *donor* neighbor (same tumor-representativeness posture as
    bridging.py's Step 6) -- verified directly against the similarity
    function's caller logic, not just trusted."""
    from synlethality.nearest_neighbor import generate_nearest_neighbor_candidates

    with SessionLocal() as db:
        # Flag every real donor's cell line as a poor model and confirm no
        # candidate is generated from it.
        real_rows = (
            _all(InteractionEffect, evidence_tier=EvidenceTier.tier_1_direct)
            + _all(InteractionEffect, evidence_tier=EvidenceTier.tier_2_inferred)
        )
        donor_cell_line_ids = {r.cell_line_id for r in real_rows}
        for cl_id in donor_cell_line_ids:
            db.get(CellLine, cl_id).tumor_concordance_flag = TumorConcordanceFlag.poor_model_mesenchymal_shift
        db.commit()

        counts = generate_nearest_neighbor_candidates(db)
        db.commit()
        assert counts["generated"] == 0, (
            "no candidates should generate once every real donor is flagged "
            "as a poor tumor model")


def test_cell_line_similarity_uses_real_depmap_expression_when_available():
    """Real expression-based similarity (scripts/extract_depmap_expression.py
    -> data/depmap/curated_cell_line_expression.json, DepMap 24Q4's own
    expression matrix restricted to the two real gene sets already cached
    by ingest/msigdb.py): blended in for any pair where both lines have a
    real profile, with a graceful, undisguised fallback to mutation+tissue
    only when either doesn't (2026-09-23: true only for MCF-10A, the one
    non-malignant curated line, in this release)."""
    from synlethality.nearest_neighbor import _load_expression_cache, cell_line_similarity

    cache = _load_expression_cache()
    if not cache:
        pytest.skip("data/depmap/curated_cell_line_expression.json not present -- "
                    "run scripts/extract_depmap_expression.py first.")

    with SessionLocal() as db:
        rko = db.get(CellLine, "RKO_LARGE_INTESTINE")
        hct = db.get(CellLine, "HCT116_LARGE_INTESTINE")
        mcf10a = db.get(CellLine, "MCF10A_BREAST")

        assert rko.cell_line_id in cache and hct.cell_line_id in cache
        assert mcf10a.cell_line_id not in cache, (
            "MCF-10A is expected to be genuinely absent from this DepMap "
            "expression release -- if this now fails, the real data has "
            "changed and this test (and the module docstring) needs updating")

        with_expression = cell_line_similarity(rko, hct, expression_cache=cache)
        without_expression = cell_line_similarity(rko, hct, expression_cache={})
        # Both real (same tissue, some shared mutation) but genuinely
        # different real numbers -- the expression term must actually
        # contribute, not silently no-op.
        assert with_expression != without_expression

        # Falls back gracefully (no crash, no fabricated expression term)
        # for a pair where one line has no real expression profile.
        fallback = cell_line_similarity(rko, mcf10a, expression_cache=cache)
        assert fallback == cell_line_similarity(rko, mcf10a, expression_cache={})


def test_prism_repurposing_ingest_attaches_real_monotherapy_viability():
    """Real ingestion step (data/prism/{Extended_Primary_Compound_List,
    Extended_Primary_Data_Matrix}.csv, PRISM Repurposing Public 24Q2 via
    Figshare, doi:10.6084/m9.figshare.25917643.v1): must run after
    DepmapPrismIngest, attach real per-cell-line LFC values only to drugs
    that already exist, correctly redirect the 12 CURATED_DRUG_ALIASES
    compounds to their curated drug_id rather than a DPC- duplicate, and
    never fabricate a value for a genuinely absent drug (lomustine)."""
    from synlethality.ingest.depmap_prism import CURATED_DRUG_ALIASES, DepmapPrismIngest
    from synlethality.ingest.prism_repurposing import SOURCE_TAG, PrismRepurposingIngest
    from synlethality.models import Drug, DrugResponse, MetricType

    with SessionLocal() as db:
        DepmapPrismIngest().run(db)
        db.commit()

        run = PrismRepurposingIngest().run(db)
        db.commit()
        assert run.status == "success", run.message
        assert run.row_count > 50_000  # real, large monotherapy dataset

        responses = _all(DrugResponse)
        assert len(responses) == run.row_count
        for r in responses[:50]:
            assert r.metric_type == MetricType.lfc_2_5um_5d
            assert r.source == SOURCE_TAG
            assert isinstance(r.viability_metric, float)

        # Every response row's drug_id must be a drug that actually exists
        # (never fabricated), and never one of the 12 alias DPC- ids, which
        # ingest/depmap_prism.py never creates a row for in the first place.
        known_drug_ids = {d.drug_id for d in _all(Drug)}
        for r in responses:
            assert r.drug_id in known_drug_ids
            assert r.drug_id not in CURATED_DRUG_ALIASES

        # Spot-check: real monotherapy data now attaches to curated drug_ids
        # that DepMap's own registry lists under a different identity.
        for curated_id in ("metformin", "cisplatin", "paclitaxel", "temozolomide",
                           "erastin", "triapine", "doxorubicin"):
            rows = _all(DrugResponse, drug_id=curated_id)
            assert rows, f"{curated_id} should have real PRISM responses via its alias redirect"

        # Genuinely absent from this compound catalog under any checked
        # name/synonym -- zero rows, not a guessed/fabricated one.
        assert _all(DrugResponse, drug_id="lomustine") == []

        # Idempotent: re-running updates in place, never duplicates.
        run2 = PrismRepurposingIngest().run(db)
        db.commit()
        assert run2.status == "success"
        assert len(_all(DrugResponse)) == len(responses)


def test_msigdb_and_geo153830_ingest_backfill_real_signature_scores():
    """Real ingestion (2026-09-22): synlethality/ingest/msigdb.py fetches the
    real Hallmark ROS-pathway and KEGG Hippo-pathway gene sets (via
    Enrichr's public MSigDB/KEGG mirror, since gsea-msigdb.org itself gates
    downloads behind a login); synlethality/ingest/geo_modifiers.py computes
    real per-gene log2FC from GSE153830's own published FPKM matrix and
    backfills the four matching stress_signature_score rows'
    previously-NULL `score` field via
    synlethality.signature_correlation.geneset_enrichment_score. Never
    creates a new stress_signature_score row, never fabricates a value for
    a (modifier, cell_line) pair with no verified real gene-set mapping."""
    from synlethality.ingest.geo_modifiers import SAMPLE_GROUPS, GEOModifierIngest
    from synlethality.ingest.msigdb import MSigDBIngest

    with SessionLocal() as db:
        before = {
            key: db.query(StressSignatureScore)
            .filter_by(modifier_id=mid, cell_line_id=cid).one().score
            for (mid, cid), g in SAMPLE_GROUPS.items()
            for key in [g["key"]]
        }
        assert all(v is None for v in before.values()), (
            "expected these four rows to start at score=None (curated seed)")

        msigdb_run = MSigDBIngest().run(db)
        assert msigdb_run.status == "success", msigdb_run.message
        assert msigdb_run.row_count == 2  # the two gene sets this session verified

        geo_run = GEOModifierIngest("GSE153830").run(db)
        assert geo_run.status == "success", geo_run.message
        assert geo_run.row_count == len(SAMPLE_GROUPS)

        rows_by_key = {}
        for (mid, cid), g in SAMPLE_GROUPS.items():
            row = db.query(StressSignatureScore).filter_by(
                modifier_id=mid, cell_line_id=cid).one()
            rows_by_key[g["key"]] = row
            assert row.score is not None
            assert isinstance(row.score, float)
            assert row.raw_deg_evidence_ref.startswith("geo:GSE153830")
            assert "[Real DEG backfill" in row.notes
            assert "uncorrected standardized-mean-difference" in row.notes

        # Real, directionally-plausible result: the paper's own headline
        # finding (NRF2/ferroptosis-axis involvement under glucose
        # deprivation in T47D) comes back as a real, strongly positive
        # enrichment z-score -- not a fabricated confirmation, an actual
        # computed number from the paper's own expression matrix.
        assert rows_by_key["t47d_glucose_nrf2"].score > 2.0

        # The full real per-gene log2FC table (not just each gene set's
        # enrichment score) is also persisted, for signature_correlation.py's
        # xsum_correlation to consume later -- see
        # test_correlate_modifier_drug_runs_real_xsum_against_synthetic_lincs.
        from synlethality.ingest.geo_modifiers import load_deg_cache
        hippo_rec = load_deg_cache("mcf7_glucose_hippo")
        assert hippo_rec["modifier_id"] == "MOD-GLUCOSE-RESTRICT-5PCT-96H"
        assert hippo_rec["cell_line_id"] == "MCF7_BREAST"
        assert isinstance(hippo_rec["gene_log2fc"], dict) and len(hippo_rec["gene_log2fc"]) > 10000

        # Idempotent: re-running both steps updates the same rows in place,
        # not a growing note or a duplicated backfill block.
        MSigDBIngest().run(db)
        geo_run2 = GEOModifierIngest("GSE153830").run(db)
        assert geo_run2.status == "success"
        for key, row_before in rows_by_key.items():
            row_after = db.query(StressSignatureScore).filter_by(
                modifier_id=row_before.modifier_id,
                cell_line_id=row_before.cell_line_id,
            ).one()
            assert row_after.score == pytest.approx(row_before.score)
            assert row_after.notes.count("[Real DEG backfill") == 1


def test_lincs_l1000_ingest_backfills_real_signature_refs():
    """Real ingestion (2026-09-22): synlethality/ingest/lincs_l1000.py reads
    data/lincs/curated_drug_signatures.json (produced by
    scripts/extract_lincs_signatures.py from the real, 5.4GB LINCS L1000
    Level 5 GCTX file -- GSE70138, downloaded ungated from NCBI GEO's own
    FTP, no clue.io registration needed) and backfills
    drug.induced_expression_signature_ref for the 6 curated drugs matched
    by exact pert_iname lookup. Never touches a drug with no real match
    (the other 7 curated drugs aren't in this LINCS release)."""
    from synlethality.ingest.lincs_l1000 import LincsL1000Ingest, load_gene_signature
    from synlethality.models import Drug

    matched_drugs = ("metformin", "5-fluorouracil", "mitomycin-c",
                      "doxorubicin", "paclitaxel", "temozolomide")
    unmatched_drugs = ("cisplatin", "oxaliplatin", "carboplatin",
                        "cyclophosphamide", "erastin", "triapine", "lomustine")

    with SessionLocal() as db:
        for drug_id in matched_drugs + unmatched_drugs:
            assert db.get(Drug, drug_id).induced_expression_signature_ref is None

        run = LincsL1000Ingest().run(db)
        assert run.status == "success", run.message
        assert run.row_count == len(matched_drugs)

        for drug_id in matched_drugs:
            ref = db.get(Drug, drug_id).induced_expression_signature_ref
            assert ref is not None and ref.startswith("lincs:")
            # Real signature actually retrievable, with the real 978
            # landmark genes, not an empty/placeholder record.
            sig = load_gene_signature(drug_id)
            assert len(sig) == 978
            assert all(isinstance(v, float) for v in sig.values())

        for drug_id in unmatched_drugs:
            assert db.get(Drug, drug_id).induced_expression_signature_ref is None

        # Idempotent.
        run2 = LincsL1000Ingest().run(db)
        assert run2.status == "success"
        assert run2.row_count == len(matched_drugs)


def test_gdsc_ingest_attaches_real_cross_validation_data():
    """Real ingestion (2026-09-23): synlethality/ingest/gdsc.py reads the
    real GDSC1/GDSC2 fitted dose-response tables (Sanger's own ungated FTP
    mirror -- cancerrxgene.org's web UI is Cloudflare-gated, same problem
    as MDPI/NCI's wiki elsewhere in this codebase) and attaches real AUC
    values for the 8 curated drugs and 12 curated cell lines confirmed
    present in at least one of the two releases. Never fabricates a value
    for the 5 drugs / 2 cell lines confirmed absent from both."""
    from synlethality.ingest.depmap_prism import DepmapPrismIngest
    from synlethality.ingest.gdsc import CELL_LINE_NAME_MAP, DRUG_NAME_MAP, GDSCIngest
    from synlethality.ingest.prism_repurposing import PrismRepurposingIngest
    from synlethality.models import DrugResponse, MetricType

    with SessionLocal() as db:
        DepmapPrismIngest().run(db)
        PrismRepurposingIngest().run(db)
        db.commit()

        run = GDSCIngest().run(db)
        assert run.status == "success", run.message
        assert run.row_count > 100  # a real, non-trivial count (132 as of 2026-09-23, post-dedup)

        gdsc_rows = db.query(DrugResponse).filter(DrugResponse.source.in_(["GDSC1", "GDSC2"])).all()
        assert len(gdsc_rows) == run.row_count
        for r in gdsc_rows:
            assert r.drug_id in DRUG_NAME_MAP.values()
            assert r.cell_line_id in CELL_LINE_NAME_MAP.values()
            assert r.metric_type == MetricType.auc
            assert 0.0 <= r.viability_metric <= 1.5  # real AUC scale, allowing real noise above 1.0

        # Genuinely absent drugs/cell lines never get a fabricated row.
        for absent_drug in ("metformin", "carboplatin", "erastin", "triapine", "lomustine"):
            assert not any(r.drug_id == absent_drug for r in gdsc_rows)
        for absent_cl in ("U937_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE", "MCF10A_BREAST"):
            assert not any(r.cell_line_id == absent_cl for r in gdsc_rows)

        # The actual point of pulling GDSC: a real, non-trivial number of
        # (drug, cell_line) pairs now have independent PRISM AND GDSC
        # viability data -- the cross-validation this ingestion exists for.
        prism_keys = {(r.drug_id, r.cell_line_id)
                      for r in db.query(DrugResponse).filter(DrugResponse.source.like("PRISM%")).all()}
        gdsc_keys = {(r.drug_id, r.cell_line_id) for r in gdsc_rows}
        overlap = prism_keys & gdsc_keys
        assert len(overlap) > 30

        # Idempotent.
        run2 = GDSCIngest().run(db)
        assert run2.status == "success"
        assert len(db.query(DrugResponse).filter(DrugResponse.source.in_(["GDSC1", "GDSC2"])).all()) == len(gdsc_rows)


def test_ctrp_ingest_attaches_real_cross_validation_data():
    """Real ingestion (2026-09-23): synlethality/ingest/ctrp.py reads the
    real CTRPv2 sensitivity data (extracted from the real PharmacoSet .rds
    file via scripts/extract_ctrp.R -- CTRP's own NCI data portal and FTP
    host are genuinely gone; the only remaining mirrors serve an R S4
    object pyreadr can't parse, so this uses real R itself, installed
    without admin rights, to read the object's slots directly) and
    attaches real AUC values (1 - mean recomputed AAC across real replicate
    experiments) for the 7 curated drugs / 11 curated cell lines confirmed
    present. Skipped gracefully if the real extracted CSV isn't present in
    this environment."""
    import os

    from synlethality.ingest.ctrp import CELL_LINE_NAME_MAP, DRUG_NAME_MAP, CTRPIngest
    from synlethality.ingest.depmap_prism import DepmapPrismIngest
    from synlethality.ingest.gdsc import GDSCIngest
    from synlethality.ingest.prism_repurposing import PrismRepurposingIngest
    from synlethality.models import DrugResponse, MetricType

    if not os.path.isfile(os.path.join("data", "ctrp", "ctrpv2_sensitivity.csv")):
        pytest.skip("data/ctrp/ctrpv2_sensitivity.csv not present -- run "
                    "scripts/extract_ctrp.R against a real CTRPv2.rds download "
                    "first (needs R; see ingest/ctrp.py's docstring).")

    with SessionLocal() as db:
        DepmapPrismIngest().run(db)
        PrismRepurposingIngest().run(db)
        GDSCIngest().run(db)
        db.commit()

        run = CTRPIngest().run(db)
        assert run.status == "success", run.message
        assert run.row_count > 30  # a real, non-trivial count (66 as of 2026-09-23)

        ctrp_rows = db.query(DrugResponse).filter_by(source="CTRP v2").all()
        assert len(ctrp_rows) == run.row_count
        for r in ctrp_rows:
            assert r.drug_id in DRUG_NAME_MAP.values()
            assert r.cell_line_id in CELL_LINE_NAME_MAP.values()
            assert r.metric_type == MetricType.auc
            assert 0.0 <= r.viability_metric <= 1.0

        # Genuinely absent drugs never get a fabricated row.
        for absent_drug in ("cisplatin", "carboplatin", "mitomycin-c", "triapine", "lomustine", "metformin"):
            assert not any(r.drug_id == absent_drug for r in ctrp_rows)
        for absent_cl in ("CASKI_CERVIX", "U87MG_CENTRAL_NERVOUS_SYSTEM", "MCF10A_BREAST"):
            assert not any(r.cell_line_id == absent_cl for r in ctrp_rows)

        # The real point: a real, non-trivial number of (drug, cell_line)
        # pairs now have THREE independent viability sources -- the
        # stronger three-way data-quality signal the build spec asked for.
        prism_keys = {(r.drug_id, r.cell_line_id)
                      for r in db.query(DrugResponse).filter(DrugResponse.source.like("PRISM%")).all()}
        gdsc_keys = {(r.drug_id, r.cell_line_id)
                     for r in db.query(DrugResponse).filter(DrugResponse.source.in_(["GDSC1", "GDSC2"])).all()}
        ctrp_keys = {(r.drug_id, r.cell_line_id) for r in ctrp_rows}
        three_way = prism_keys & gdsc_keys & ctrp_keys
        assert len(three_way) > 20

        # Idempotent.
        run2 = CTRPIngest().run(db)
        assert run2.status == "success"
        assert len(db.query(DrugResponse).filter_by(source="CTRP v2").all()) == len(ctrp_rows)


def test_clinical_evidence_links_are_valid():
    """Every clinical_evidence row with a link points at a real
    interaction_effect row (never a dangling/fabricated reference). Every
    row carries either a real-looking NCT id or, when none was registered
    (e.g. a pre-registry-era feasibility study), a publication_ref instead
    -- never neither."""
    rows = _all(ClinicalEvidence)
    assert len(rows) >= 2
    interaction_ids = {it.id for it in _all(InteractionEffect)}
    for ce in rows:
        assert (ce.nct_id and ce.nct_id.startswith("NCT")) or ce.publication_ref
        if ce.linked_interaction_effect_id is not None:
            assert ce.linked_interaction_effect_id in interaction_ids


def test_ingestion_stubs_refuse_to_write():
    """Structured ingestors must not fabricate data before real ETL exists:
    run() records a failed IngestionRun (no silent failure) and writes no
    domain rows. depmap_prism/prism_repurposing/msigdb/
    geo_modifiers("GSE153830")/lincs_l1000/gdsc/ctrp are no longer in this
    list -- they're real, working steps now (see
    test_depmap_prism_ingest_backfills_without_touching_curated_rows,
    test_prism_repurposing_ingest_attaches_real_monotherapy_viability,
    test_msigdb_and_geo153830_ingest_backfill_real_signature_scores,
    test_lincs_l1000_ingest_backfills_real_signature_refs,
    test_gdsc_ingest_attaches_real_cross_validation_data, and
    test_ctrp_ingest_attaches_real_cross_validation_data -- ctrp's real
    data needed installing R itself and reading its .rds file's S4 slots
    directly, since pyreadr can't parse a PharmacoSet; see
    ingest/ctrp.py's docstring for the full story).
    geo_modifiers("GSE48398") is still a real stub -- only GSE153830 has a
    reviewed parsing path (see ingest/geo_modifiers.py)."""
    from synlethality.ingest.celligner import CellignerIngest
    from synlethality.ingest.clinicaltrials_gov import ClinicalTrialsGovIngest
    from synlethality.ingest.ferrdb import FerrDBIngest
    from synlethality.ingest.geo_modifiers import GEOModifierIngest
    from synlethality.ingest.nci_cts_api import NCIClinicalTrialsIngest

    steps = [
        GEOModifierIngest("GSE48398"),
        FerrDBIngest(),
        CellignerIngest(),
        ClinicalTrialsGovIngest(),
        NCIClinicalTrialsIngest(),
    ]
    with SessionLocal() as db:
        n_before = len(db.scalars(select(InteractionEffect)).all())
        for step in steps:
            run = step.run(db)
            assert run.status == "failed", run
            assert "NotImplementedError" in run.message
        n_after = len(db.scalars(select(InteractionEffect)).all())
    assert n_before == n_after

