"""
Generate reference data files for the DRUGSYNC-NPxP implementation.

Creates:
  data/reference/genes_978.txt    — canonical 978 L1000 landmark gene symbols
  data/reference/gene_index.csv   — gene_id, gene_symbol, index (0..977)
  data/reference/ppi_edges.csv    — will be generated by src/ppi/build_graph.py
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from synlethality import config
from synlethality.signature_space import (
    load_canonical_genes,
    CANONICAL_VERSION,
    CANONICAL_SYMBOLS,
    CANONICAL_ENTREZ,
    CANONICAL_GENES,
)

REFERENCE_DIR = os.path.join(config.DATA_DIR, "reference")
os.makedirs(REFERENCE_DIR, exist_ok=True)


def write_genes_978():
    """Write the ordered list of 978 gene symbols, one per line."""
    path = os.path.join(REFERENCE_DIR, "genes_978.txt")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(CANONICAL_SYMBOLS) + "\n")
    print(f"  {path}: {len(CANONICAL_SYMBOLS)} symbols")
    return path


def write_gene_index():
    """Write gene index CSV: entrez_id, gene_symbol, index."""
    path = os.path.join(REFERENCE_DIR, "gene_index.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["entrez_id", "gene_symbol", "index"])
        for i, (entrez, symbol) in enumerate(CANONICAL_GENES):
            writer.writerow([entrez, symbol, i])
    print(f"  {path}: {len(CANONICAL_GENES)} entries")
    return path


def main():
    print(f"Canonical space: {CANONICAL_VERSION}")
    print(f"Gene count: {len(CANONICAL_SYMBOLS)}")
    print("Writing reference files...")
    write_genes_978()
    write_gene_index()
    print("Done. Reference files ready.")


if __name__ == "__main__":
    main()